package rules.keyworld.timer_rule;
import org.czy.example.keyworld.timer_rule.Server;
global  org.czy.example.keyworld.timer_rule.ResultEvent event;

rule "timerTest"
    //每1秒执行一次
    timer (cron:0/1 * * * * ?)
    when
        server : Server(times > 10)
    then
    System.out.println("已经尝试"+server.getTimes()+"次，超过预警次数！");
    event.getEvents().add(new java.util.Date() + " - 服务器已经尝试" + server.getTimes() + "次，依旧失败，特发次报警信息！");
end


